### ISSUE TITLE
Broken links in references

### ISSUE THREAD

**Issue by Eli-Levi** [ShmuelLa/Operating_Systems_Course_Summary#1]
The links added for reference are usually broken because it adds the number reference (i.e - 24 or 26 etc) to the link, which results in a broken link.
For example:
![image](https://user-images.githubusercontent.com/63515734/123631497-79900700-d81f-11eb-842f-94d203da7538.png)
Leads to: https://www.gnu.org/software/libc/manual/html_node/Blocking-Signals.html24 instead of https://www.gnu.org/software/libc/manual/html_node/Blocking-Signals.html

**Comment by ShmuelLa** [comment]
Fixed!
